projects:
  gom-api:
    schemaPath: src/db/prisma/prisma-types.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/db/prisma/prisma.binding.ts
