version: '3.7'

networks:
  multihost:

volumes:
  postgres:
  redis:

services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
      resources:
        limits:
          memory: 500M
    networks:
      - multihost
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgres:
    image: postgres:11.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
    networks:
      - multihost
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
    command: [ "redis-server", "--appendonly", "yes" ] # start with persistent storage
    networks:
      - multihost
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
