version: '3.7'

networks:
  gomnet:

volumes:
  postgres:
  redis:

secrets:
  gom_app_key:
    external: true
  gom_auth0_client_secret:
    external: true
  gom_pg_password:
    external: true
  gom_prisma_secret:
    external: true
  gom_vapid_private_key:
    external: true
  gom_vapid_public_key:
    external: true

services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
      resources:
        limits:
          memory: 500M
    networks:
      - gomnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgres:
    image: postgres:11.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      #POSTGRES_PASSWORD_FILE: /run/secrets/gom_pg_password
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
    networks:
      - gomnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    secrets:
      - gom_pg_password
  
  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 1
    command: [ "redis-server", "--appendonly", "yes" ] # start with persistent storage
    networks:
      - gomnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
